name: Elasticsearch Fly Image CI

on:
  push:
    branches: [ "7.16", "7.17", "8.0", "8.1", "8.2", "8.3", "8.4"]
  pull_request:
    branches: [ "7.16", "7.17", "8.0", "8.1", "8.2", "8.3", "8.4"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        DOCKER_BUILDKIT: 0
